language: node_js
node_js:
- '0.10'
cache:
  directories:
  - node_modules
after_success:
- npm run coveralls
notifications:
  slack:
    secure: kwt3fB+6ewktnDHjPWqK4k/pJ6QPSNwWB9jT+tIU1hfR04eEakXvg76fSsXPOXKbufPkXvyoeV17rm+pnr9yFHlmHDE1qOz0Is8vLKxuMr9wHAHjA06dVWl7ig69wPyEqFPbmque9L9xu0JCnZtpr8bv6CJW0B1eysCoAjNb0Ng=
